// Log in as Reinhardt
POST http://localhost:5014/auth/login
Content-Type: application/json

{
  "username": "Reinhardt",
  "password": "123"
}

###

POST http://localhost:5014/users
Content-Type: application/json

{
  "username": "TestName",
  "password": "123"
}